name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Stan Version
        run: |
          echo "::set-env name=STAN_VERSION::2.19.1"

      - name: Install Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.11

      - name: Install Stan
        run: .github/scripts/install_deps.sh
      
      - name: Test
        run: |
          source .github/scripts/env.sh
          sbt -batch test it:test
